---
    extends: ["vkbansal", "vkbansal/babel"]
    rules:
        camelcase: 0
        max-statements: 0
        no-labels: 0
        no-param-reassign: 0
        one-var: 0
        no-console: 0
        prefer-template: 0
